### PR TITLE
Ability to define optional wait time for long polling support

### PR DESCRIPTION
**Pull request by phillipsnick**
Provide long polling support as an optional input parameter at the console. This allows me to define the maximum 20 seconds 

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html

### CODE REVIEW

**Comment by mcfedr** [comment]
Thanks.

**Comment by mcfedr** [comment]
Now I look I see that my logic for long polling was broken, it should have been `count($urls) > 1 ? 0 : 20`
My logic here is that if you are polling multiple queues in the same runner, you probably don't want long polling because jobs might appear on one queue, but it wont be processed until `waitTime` is reached on each queue before it in the loop.
I have fixed this in 74bca4ac84b7610b2bdfca42e9be79537ad28e13, whilst keeping your changes to allow waitTime to be overridden.

**Comment by phillipsnick** [comment]
Ah that makes more sense, didn't even think of that.

In theory you could have a Symfony process per queue? But that's a bit more complicated.

**Comment by mcfedr** [comment]
Yes, running multiple queues with the same runner makes them have a priority, because it will always take jobs from the first queue, and only if there are none, then it takes from the second, etc. 

In my production app I have 3 queues, one is run independently, on one machine, using `--queue=a` and the other two are run together with `--queue=b,c` - `c` queue tasks are low priority

**Pull request merged**
